### ISSUE TITLE
Dependency 'yireo/module-admin-simple-search-fields' missing

### ISSUE THREAD

**Issue by c-walter** [yireo/Yireo_EmailTester2#15]
With the Version 1.7.6 the admin view does not work properly. The error `Class "Yireo\AdminSimpleSearchFields\ViewModel\CustomerField" does not exist`  is shown when admin view is called.

In the composer.json there is no require for the `yireo/module-admin-simple-search-fields` only for `yireo/magento2-admin-react-components` which does also not require `yireo/module-admin-simple-search-fields`

**Comment by jissereitsma** [comment]
This is a big miss - the swap in supporting module was made a while ago but still pending some fixes (including the composer dependency). However, this was suddenly released without properly testing.

The composer dependency is now being mentioned in 1.7.7. Note that the other module is now renamed to `yireo/magento2-admin-simple-search-fields`.

Does this fix things for you?

**Comment by c-walter** [comment]
This only fixes the first part of the issue.
In https://github.com/yireo/Yireo_EmailTester2/blob/master/etc/module.xml#L26 there is still a dependency to the AdminReactComponents-Module and in https://github.com/yireo/Yireo_EmailTester2/blob/master/view/adminhtml/layout/emailtester_index_index.xml#L19 it seems to require the AdminReactComponent-Module.

If I require the AdminReactComponent-Module manually it looks better, there are "debug" links in the value fields which causes an error for the customer value field. And with a quick check the values are not saved anymore once a mail is sent

**Comment by jissereitsma** [comment]
I have updated both modules now, finalizing the refactoring that should have been done ages ago. Does it work for you?

**Comment by c-walter** [comment]
The 1.7.8 looks good now, thanks for the quick help and fixes.

This might not be related to the topic, but the "Search"-Overlays, don't allow to paginate or to search properly. As a workaround you can search for the customer / product / order and enter the ID directly

**Comment by jissereitsma** [comment]
The search was an issue indeed - but this is now fixed. Pagination is still on the todo list. Glad it (kind of) works again!
