### ISSUE TITLE
Unit test error while running

### ISSUE THREAD

**Issue by bbakalov** [yireo/Yireo_EmailTester2#16]
**Module installed via composer**

I've tried to run unit test by the command from [here](https://github.com/yireo/Yireo_EmailTester2/blob/master/TESTING.md) and got an error
```
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

Test directory "./vendor/yireo/magento2-emailtester2/../../../app/code/Yireo/EmailTester2/Test/Unit" not found
app@97c99d5f12d9:~/html$ ./vendor/bin/phpunit -c vendor/yireo/magento2-emailtester2/phpunit.xml.yireo
```

After deleting `<directory suffix="Test.php">../../../app/code/Yireo/EmailTester2/Test/Unit</directory>` it works as expected

**Comment by jissereitsma** [comment]
You are totally correct. However, the point of testsuites is that they are specific for environments and easily customized. I've updated the doc so you simply can point PHPUnit towards the testing folder. You don't need testsuites,
