### ISSUE TITLE
Composer issue on install

### ISSUE THREAD

**Issue by asim-blueprintprep** [yireo/Yireo_EmailTester2#3]
After running:
`php8 /usr/local/bin/composer2 require yireo/magento2-emailtester2`
it errors with:

`Higher matching version 1.6.24 of yireo/magento2-emailtester2 was found in public repository packagist.org                                     
                               than 1.6.19 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,   
                               please investigate and update package requirement to match the version from the private repository `

**Comment by jissereitsma** [comment]
This extension was once hosted on the Magento Marketplace, but has now been removed there. Unfortunately, they don't clean things up. You can make the marketplace repository non-canonical to fix this: https://getcomposer.org/doc/articles/repository-priorities.md#making-repositories-non-canonical

**Comment by asim-blueprintprep** [comment]
Thanks for the info :) Closing as the issue lies elsewhere
