### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dennismetz** [yireo/Yireo_EmailTester2#7]
Hi together,
I found the extension earlier and would like to test it, but unfortunately I don't really know how to use it (maybe I'm missing something).

Under Shops -> Configuration -> YIREO I have entered everything but I do not see a new page or the buttons to test...

I use Magento 2.4.5-p1

**Comment by jissereitsma** [comment]
And what about **Marketing > Communications**? Also, under **Stores** (not **Shops**, that's not the real English words) and then **Configuration > Yireo > EmailTester** there should be a configuration section available. If it not there, you need to troubleshoot the extension installation. Which steps did you take to install this installation and which steps did you take to verify this?

**Comment by dennismetz** [comment]
Oh, sorry for the error - the backend is not set to English on my end.
Under Marketing > Communications I have found the setting now! Thanks a lot!
Did I miss that in the doc? If so, sorry for that too...
