### ISSUE TITLE
Preview Email not working

### ISSUE THREAD

**Issue by MLisiecki** [yireo/Yireo_EmailTester2#8]
I got this error:

main.CRITICAL: Error: Call to undefined method Magento\Framework\Mail\Template\TransportBuilder\Interceptor::getMessage() in vendor/yireo/magento2-emailtester2/Model/Mailer.php:229

Sending mail still working :)

**Comment by jissereitsma** [comment]
Thanks. Which version of Magento are you using and which version of this EmailTester?

**Comment by MLisiecki** [comment]
Oh, sorry, latest version of EmailTester (installed via composer) and Magento wer. 2.4.3-p2. I have checked - in TransportBuilder.php there is no any getMessage() function.

**Comment by MLisiecki** [comment]
Yes, I have check it and You have right. It strange, because I did all necessary steps. Anyway, it seems it must be a problem at my side. Thank You for Your time! :)
